#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR/.."
VERSION=$(tr -d '[:space:]' < "$PROJECT_DIR/VERSION")

OUTPUT="$PROJECT_DIR/Sources/EasyTierHelperShared/Version.generated.swift"
cat > "$OUTPUT" << EOF
// Generated by scripts/generate-version.sh — do not edit manually
public enum AppVersion {
    public static let current = "$VERSION"
}
EOF

echo "Generated $OUTPUT (version $VERSION)"
