#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR/.."
VERSION_FILE="$PROJECT_DIR/VERSION"
OUTPUT_FILE="$PROJECT_DIR/Sources/EasyTierManager/Utilities/Version.generated.swift"

if [ ! -f "$VERSION_FILE" ]; then
    echo "Error: VERSION file not found at $VERSION_FILE"
    exit 1
fi

VERSION=$(tr -d '[:space:]' < "$VERSION_FILE")

if [ -z "$VERSION" ]; then
    echo "Error: VERSION file is empty"
    exit 1
fi

cat > "$OUTPUT_FILE" << EOF
// Generated by scripts/generate-version.sh — do not edit manually
enum AppVersion {
    static let current = "$VERSION"
}
EOF

echo "Generated $OUTPUT_FILE with version $VERSION"
